
type User {
  id: ID!
  firstName: String
  lastName: String
  email: String
}

type Query {
  getUsers: [User]
}

type Mutation {
  addUser(firstName: String!, lastName: String!, email: String!): User
}